sonar.projectKey=Sopra-Steria-Code-Academy_CodeAcademy2026_18057138-f0a0-4832-a25f-656706baa85a

# Source directories
sonar.sources=.

# Java configuration
sonar.java.source=21
sonar.java.binaries=2-EventDriven/java-consumer/target/classes

# .NET configuration
sonar.cs.dotnet.binaries=2-EventDriven/dotnet-consumer/bin

# Exclusions
sonar.exclusions=**/node_modules/**,**/.next/**,**/target/**,**/bin/**,**/obj/**,**/.yarn/**,**/coverage/**