services:
  app:
    build:
      context: ../idempotweet
      dockerfile: ../2-Docker/Dockerfile
    # image: ghcr.io/${GITHUB_REPOSITORY}:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://codeacademy:codeacademy@postgres:5432/codeacademy
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: codeacademy
      POSTGRES_PASSWORD: codeacademy
      POSTGRES_DB: codeacademy
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
