name: CI

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:

    name: Build with bun latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v5
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn test

  check:

    name: Run all checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build with bun latest
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint check
        run: bun lint

      - name: Type check
        run: bun check-types