spring.application.name=codeacademy
server.port=8080
server.max-http-request-header-size: 10MB

rabbitmq.userName=guest
rabbitmq.password=guest
rabbitmq.host=localhost
rabbitmq.vhost=/
#rabbitmq.port=5671
#rabbitmq.userName=admin
#rabbitmq.password=obiF+cSQFYlUWnIk7XJubTEjRNYfTvAT
#rabbitmq.host=amqps://academy:q%2Frxh8xxRv67QzV4mwDPuMEhg5Y3diZE@rabbitmq.thawi.no
