name: CI
on:
  pull_request:
    paths:
      - '1-DevOps/idempotweet/**'
  workflow_call:
  workflow_dispatch:
jobs:
  name: CI
  runs-on: ${{ vars.RUNNER || 'self-hosted' }}
  defaults:
    run:
      working-directory: 1-DevOps/idempotweet
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Enable corepack
      run: corepack enable

    - name: Install dependencies
      run: yarn install --immutable

    - name: Run tests
      run: yarn test

    - name: Run test coverage
      run: yarn test:coverage
