spring.application.name=codeacademy
spring.profiles.active=production
server.port=8080
server.max-http-request-header-size=10MB

spring.datasource.url=jdbc:postgresql://host.docker.internal:5435/codeacademy
spring.datasource.username=codeacademy
spring.datasource.password=codeacademy

# Optional: Explicitly define the driver (usually auto-detected)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true

rabbitmq.userName=guest
rabbitmq.password=guest
rabbitmq.host=localhost
rabbitmq.vhost=/
rabbitmq.port=5672
remote.rabbitmq.userName=${REMOTE_RABBITMQ_USERNAME:guest}
remote.rabbitmq.password=${REMOTE_RABBITMQ_PASSWORD:guest}
remote.rabbitmq.host=${REMOTE_RABBITMQ_HOST:localhost}
remote.rabbitmq.vhost=/
remote.rabbitmq.port=${REMOTE_RABBITMQ_PORT:5672}
remote.rabbitmq.useSsl=${REMOTE_RABBITMQ_SSL:false}

logging.level.no.soprasteria=INFO

