name: CI
on:
  pull_request:
    paths:
      - '1-DevOps/idempotweet/**'
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-DevOps/idempotweet
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@v6.3.0
        with:
          cache: yarn
          cache-dependency-path: 1-DevOps/idempotweet/yarn.lock

      - name: Activate coreback
        run: corepack enable
        working-directory: .

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Generate Test Coverage
        run: yarn test:coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: 1-DevOps/idempotweet
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}